services:
  user-service-db:
    image: postgres:17
    container_name: user-service-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user-service
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
      - ./postgres/user-service/schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  auth-service-db:
    image: postgres:17
    container_name: auth-service-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth-service
    ports:
      - "5433:5432"
    networks:
      - backend
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
      - ./postgres/auth-service/schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  package-service-mongo:
    image: mongo:7
    container_name: package-service-mongo
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - package_mongo_data:/data/db
      - ./mongo/package-service/validation.js:/docker-entrypoint-initdb.d/01_validation.js
      - ./mongo/package-service/data.js:/docker-entrypoint-initdb.d/02_data.js
    restart: unless-stopped

  delivery-service-db:
    image: postgres:17
    container_name: delivery-service-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=delivery-service
    ports:
      - "5435:5432"
    networks:
      - backend
    volumes:
      - delivery_postgres_data:/var/lib/postgresql/data
      - ./postgres/delivery-service/schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    image: user-service:latest
    volumes:
      - user_service_data:/var/lib/user-service
    networks:
      - backend
    depends_on:
      user-service-db:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    image: auth-service:latest
    volumes:
      - auth_service_data:/var/lib/auth-service
    networks:
      - backend
    depends_on:
      auth-service-db:
        condition: service_started
      user-service:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
#
  package-service:
    build:
      context: ./services/package-service
      dockerfile: Dockerfile
    image: package-service:latest
    volumes:
      - package_service_data:/var/lib/package-service
    networks:
      - backend
    depends_on:
      package-service-mongo:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  delivery-service:
    build:
      context: ./services/delivery-service
      dockerfile: Dockerfile
    image: delivery-service:latest
    volumes:
      - delivery_service_data:/var/lib/delivery-service
    networks:
      - backend
    depends_on:
      delivery-service-db:
        condition: service_started
      user-service:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    depends_on:
      user-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      package-service:
        condition: service_healthy
      delivery-service:
        condition: service_healthy
    restart: unless-stopped

  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./docs:/usr/share/nginx/html/specs:ro
    environment:
      BASE_URL: /docs
      URLS: >-
        [
          {"url":"/docs/specs/auth-service.yaml","name":"Auth Service"},
          {"url":"/docs/specs/user-service.yaml","name":"User Service"},
          {"url":"/docs/specs/package-service.yaml","name":"Package Service"},
          {"url":"/docs/specs/delivery-service.yaml","name":"Delivery Service"}
        ]
      URLS_PRIMARY_NAME: "Auth Service"
    networks:
      - backend
    restart: unless-stopped

volumes:
  user_postgres_data:
  auth_postgres_data:
  package_mongo_data:
  delivery_postgres_data:

  user_service_data:
  auth_service_data:
  package_service_data:
  delivery_service_data:

networks:
  backend:
    driver: bridge