worker-threads: 2
worker-fs-threads: 2
logger-level: debug

is-testing: true

server-port: 8080

jwt-secret: "test-secret-key"

sqlite-db-path: "/tmp/auth-service-test.db"

user-service-url: "http://localhost:8081/users"