components_manager:
    task_processors:
        main-task-processor:
            worker_threads: $worker-threads

        fs-task-processor:
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    coro_pool:
        stack_usage_monitor_enabled: false

    components:
        server:
            listener:
                port: $server-port
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard

        testsuite-support: {}

        dns-client:
            fs-task-processor: fs-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        secdist:
            provider: default-secdist-provider

        default-secdist-provider:
            config: $secdist

        my-rabbit:
            secdist_alias: delivery-rabbit
            min_pool_size: 5
            max_pool_size: 10
            max_in_flight_requests: 5
            use_secure_connection: false

        consumer-notification:
            rabbit_name: my-rabbit
            queue: notification-queue
            prefetch_count: 10
