worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

dbconnection: "postgresql://postgres:postgres@auth-service-db:5432/auth-service"

user-service-url: "http://user-service:8080/v1"

jwt-secret: "change-me-in-production-use-a-long-random-secret"

secdist-path: "/etc/auth_service/secdist.json"
